'use strict';
require('./testSetup'); const request=require('supertest'); const createApp=require('../app'); const app=createApp();
const integrity={'X-Legacy-Pulse-Request':'1'};
describe('Auth flow',()=>{
 const creds={email:'alice@example.com',password:'CorrectHorse9',fullName:'Alice Owner'};
 test('registers a new user',async()=>{const r=await request(app).post('/api/auth/register').send(creds);expect(r.status).toBe(201);expect(r.body.accessToken).toBeTruthy();expect(JSON.stringify(r.body)).not.toContain(creds.password);});
 test('rejects duplicate registration',async()=>{const r=await request(app).post('/api/auth/register').send(creds);expect(r.status).toBe(409);});
 test('rejects weak passwords',async()=>{const r=await request(app).post('/api/auth/register').send({email:'bob@example.com',password:'short',fullName:'Bob'});expect(r.status).toBe(400);});
 test('logs in with correct credentials and sets a refresh cookie',async()=>{const r=await request(app).post('/api/auth/login').send({email:creds.email,password:creds.password});expect(r.status).toBe(200);expect(r.body.accessToken).toBeTruthy();expect(r.headers['set-cookie'].some(c=>c.startsWith('lp_refresh=')&&/HttpOnly/i.test(c))).toBe(true);});
 test('rejects login with wrong password',async()=>{expect((await request(app).post('/api/auth/login').send({email:creds.email,password:'wrongpassword1'})).status).toBe(401);});
 test('rejects login for nonexistent user with same error shape',async()=>{const a=await request(app).post('/api/auth/login').send({email:'nobody@example.com',password:'whatever123'});const b=await request(app).post('/api/auth/login').send({email:creds.email,password:'wrongpassword1'});expect(a.status).toBe(401);expect(b.status).toBe(401);expect(a.body.error.message).toBe(b.body.error.message);});
 test('GET /auth/me requires a valid access token',async()=>{expect((await request(app).get('/api/auth/me')).status).toBe(401);const l=await request(app).post('/api/auth/login').send({email:creds.email,password:creds.password});const a=await request(app).get('/api/auth/me').set('Authorization',`Bearer ${l.body.accessToken}`);expect(a.status).toBe(200);});
 test('rejects malformed access token',async()=>{expect((await request(app).get('/api/auth/me').set('Authorization','Bearer not.a.valid.jwt')).status).toBe(401);});
 test('refresh rotates token and requires request-integrity header',async()=>{const l=await request(app).post('/api/auth/login').send({email:creds.email,password:creds.password});const cookie=l.headers['set-cookie'];expect((await request(app).post('/api/auth/refresh').set('Cookie',cookie)).status).toBe(401);const r=await request(app).post('/api/auth/refresh').set('Cookie',cookie).set(integrity);expect(r.status).toBe(200);expect(r.body.accessToken).toBeTruthy();expect((await request(app).post('/api/auth/refresh').set('Cookie',cookie).set(integrity)).status).toBe(401);});
 test('logout revokes refresh token and requires request-integrity header',async()=>{const l=await request(app).post('/api/auth/login').send({email:creds.email,password:creds.password});const cookie=l.headers['set-cookie'];expect((await request(app).post('/api/auth/logout').set('Cookie',cookie)).status).toBe(401);expect((await request(app).post('/api/auth/logout').set('Cookie',cookie).set(integrity)).status).toBe(204);expect((await request(app).post('/api/auth/refresh').set('Cookie',cookie).set(integrity)).status).toBe(401);});
 test('login is rate limited after repeated failures',async()=>{jest.resetModules();process.env.AUTH_RATE_LIMIT_MAX='5';const freshCreateApp=require('../app');const freshApp=freshCreateApp();const attempts=[];for(let i=0;i<8;i++)attempts.push(await request(freshApp).post('/api/auth/login').send({email:'ratelimit@example.com',password:'wrong'}));expect(attempts.map(r=>r.status)).toContain(429);delete process.env.AUTH_RATE_LIMIT_MAX;});
});
